version: '3'
services:
  gekko:
    build: ./
    container_name: "gekko"
    volumes:
      - ./:/usr/src/app
    environment:
     - NODE_PATH=/usr/src/node_modules;/usr/src/node_modules_exchanges
     - HOST
     - PORT
     - USE_SSL
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}:${PORT}"
